#!/usr/bin/env bash
# Transfers a file from client to server using scp

# Check if exactly 4 parameters are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign arguments to variables
FILE_PATH=$1
SERVER_IP=$2
SERVER_USER=$3
SSH_KEY=$4

# Transfer file to the user's home directory on the server
scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$SERVER_USER@$SERVER_IP:~/"
