#!/usr/bin/env bash
# Installs and configures Nginx to serve 'Holberton School' on port 80
apt-get update -y
apt-get install nginx -y

echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Restart Nginx without systemctl
service nginx restart
