#!/usr/bin/env bash
# Installs and configures Nginx to serve 'Holberton School' on port 80

apt-get update -y
apt-get install nginx -y

# Replace the default page content
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Restart Nginx (without systemctl)
service nginx restart

