#!/usr/bin/env bash
# Configures Nginx to serve a custom 404 page

# Update & install nginx
apt-get update -y
apt-get install -y nginx

# Make sure nginx is running
service nginx start

# Create custom 404 page
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Configure Nginx default site to use the custom 404 page
cat > /etc/nginx/sites-available/default << 'EOF'
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }

    error_page 404 /custom_404.html;
    location = /custom_404.html {
        internal;
    }
}
EOF

# Reload Nginx
service nginx restart
